steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Image'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/emoji-app:$SHORT_SHA', 
      '.'
    ]

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Image'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/emoji-app:$SHORT_SHA'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'emoji-sentiment-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/emoji-app:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/emoji-app:$SHORT_SHA'